// ===========================================================================
// bench/competitors/report-competitors.ts
//
// Runs the competitor comparison and writes the recorded baseline.
//
//   npx ts-node --project bench/tsconfig.json bench/competitors/report-competitors.ts
//
// Not only the wins get recorded. The losses go in the same table, and so
// does the count of disagreements. A benchmark that publishes its losses is
// worth more than one that does not — or rather, one that publishes only its
// wins proves nothing at all.
// ===========================================================================
import * as fs from "fs";
import * as path from "path";
import { describeMachine } from "../describe-machine";
import { BENCH_SHAPES } from "../shapes/index";
import { COMPETITORS } from "./index";
import { measureAllAgreement } from "./measure-agreement";
import { measureCompetitorRatio } from "./measure-competitor-ratio";

const OUTPUT = path.join(
  __dirname,
  "..",
  "..",
  "config",
  "competitor-baseline.json"
);

/**
 * Shapes an already-taken agreement measurement for the report. **It does not
 * measure.** Taking the measurement as an argument is what lets the caller
 * write out the same one it judged; measuring again here would make the
 * recorded figures a different set from the judged ones.
 */
export function summariseAgreement(
  measured: ReturnType<typeof measureAllAgreement>
): readonly unknown[] {
  return measured.map((entry) => ({
    shape: entry.shape,
    competitor: entry.competitor,
    agreedValues: entry.agreedValues.length,
    disagreements: entry.disagreements.map((one) => ({
      luqSaid: one.luqSaid,
      value: JSON.stringify(one.value)?.slice(0, 200) ?? String(one.value),
    })),
  }));
}

/** Every shape against every competitor. Pairings answering undefined drop out. */
export function measureAllRatios(): readonly MeasuredRatio[] {
  const measured: MeasuredRatio[] = [];
  for (const shape of BENCH_SHAPES) {
    for (const competitor of COMPETITORS) {
      const ratio = measureCompetitorRatio(shape, competitor);
      if (ratio !== undefined) measured.push(ratio);
    }
  }
  return measured;
}

export interface MeasuredRatio {
  readonly shape: string;
  readonly competitor: string;
  readonly ratio: number;
}

/**
 * Builds and writes the report from measurements already taken.
 *
 * Measuring and writing are separate because the check needs the same
 * measurement. Measuring independently in both timed every matchup twice,
 * which was about half the job.
 */
/**
 * Who is allowed to record the published figures.
 *
 * CI's runner, or a person who has said out loud that they are replacing a CI
 * measurement with a local one.
 *
 * The ratios here are machine-relative, and this file's own header already
 * records that the assumption a ratio cancels the runner out "has already been
 * disproved in this repository". So a baseline recorded on a laptop and one
 * recorded on the runner are not interchangeable — and there was nothing
 * stopping the first from quietly replacing the second. It happened during the
 * review that produced this guard: an EPYC/linux record was overwritten by a
 * Windows one, which changes the machine and the competitor versions in the
 * same commit and leaves nobody able to say which moved a number.
 *
 * `--local` is the deliberate way through, and it is meant to be visible in a
 * diff: the machine block in the written file says what it ran on.
 */
function refuseToRecordOutsideCi(): void {
  const inCi = process.env["CI"] === "true" || process.env["CI"] === "1";
  if (inCi || process.argv.includes("--local")) return;
  throw new Error(
    "config/competitor-baseline.json is the published comparison and is recorded on CI's runner.\n" +
      "Ratios move with the machine, so a local recording is not a drop-in replacement for one.\n" +
      "Run it in CI, or pass --local if you mean to replace the record from this machine."
  );
}

export function writeCompetitorReport(
  agreement: readonly unknown[],
  measured: readonly MeasuredRatio[]
): void {
  refuseToRecordOutsideCi();
  const report = {
    note: [
      "Luq and each competitor, measured alternately in one process. Generated by bench/competitors/.",
      "ratio is the per-pair median of luq_ops / competitor_ops. Above 1 means Luq is faster.",
      "Only values both libraries agreed on were timed. Disagreements are kept in the agreement section.",
      "ajv is fast because it generates the validation function as code, so the number alone does not explain itself.",
      "But 'ajv cannot be used under a strict CSP' is wrong: compiled ahead of time through its standalone build,",
      "the output contains neither new Function nor eval (generated and checked, not assumed).",
      "The difference only appears when the schema arrives at run time — from a server, from a database,",
      "written by the user. Ahead-of-time compilation is impossible then, and ajv falls back to generating code.",
      "Luq turns a run-time document into rules without generating code, so it still works there.",
    ],
    machine: describeMachine(),
    competitors: COMPETITORS.map((one) => ({
      name: one.name,
      version: one.version,
    })),
    agreement,
    measured,
  };

  fs.writeFileSync(OUTPUT, `${JSON.stringify(report, null, 2)}\n`, "utf8");
  process.stdout.write(
    `config/competitor-baseline.json: recorded ${measured.length} pairings
`
  );
}

function run(): void {
  writeCompetitorReport(
    summariseAgreement(measureAllAgreement(COMPETITORS)),
    measureAllRatios()
  );
}

// **Runs only when this module is the entry point.** Without the guard,
// importing measureAllRatios from here would run all of it and overwrite the
// recorded baseline — the very double measurement this arrangement removes.
if (require.main === module) {
  run();
}
