import * as fs from "fs";
import * as path from "path";

export const GENERATED_BANNER = [
  "// GENERATED FILE - do not edit by hand.",
  "// Generated by scripts/catalog/build-plugin-catalog.ts out of the plugin directory structure.",
].join("\n");

/** Creates the parent directory, then writes. Identical content is not written, leaving mtime alone. */
export function writeGeneratedFile(
  repositoryRoot: string,
  relativePath: string,
  contents: string
): boolean {
  const absolutePath = path.join(repositoryRoot, relativePath);
  fs.mkdirSync(path.dirname(absolutePath), { recursive: true });
  if (
    fs.existsSync(absolutePath) &&
    fs.readFileSync(absolutePath, "utf8") === contents
  ) {
    return false;
  }
  fs.writeFileSync(absolutePath, contents, "utf8");
  return true;
}
