#!/bin/bash
export LD_LIBRARY_PATH="/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib:$LD_LIBRARY_PATH"
exec /mnt/c/projects/luq/compiler/target/release/luq-lsp "$@"
