// GENERATED by scripts/generate-size-data.mjs — do not edit.
// Source of truth: config/size-budget.json, which scripts/measure-bundle-size.ts
// re-measures against on every build.

export const bundleSize = {
  coreOnly: {
    bytes: 7590,
    gzip: "7,590 B",
    ceiling: 8000,
  },
  onePlugin: {
    bytes: 7719,
    gzip: "7,719 B",
    ceiling: 8250,
  },
  threePlugin: {
    bytes: 8090,
    gzip: "8,090 B",
    ceiling: 8600,
  },
  sixPlugin: {
    bytes: 8475,
    gzip: "8,475 B",
    ceiling: 9000,
  },
  fullFeature: {
    bytes: 25607,
    gzip: "25,607 B",
    ceiling: 26100,
  },
  legacyCoreGzip: 17423,
} as const;
