// GENERATED by scripts/generate-size-data.mjs — do not edit.
// Source of truth: config/size-budget.json, which scripts/measure-bundle-size.ts
// re-measures against on every build.

export const bundleSize = {
  coreOnly: {
    bytes: 8447,
    gzip: "8,447 B",
    ceiling: 8579,
  },
  onePlugin: {
    bytes: 8586,
    gzip: "8,586 B",
    ceiling: 8718,
  },
  threePlugin: {
    bytes: 8912,
    gzip: "8,912 B",
    ceiling: 9049,
  },
  sixPlugin: {
    bytes: 9333,
    gzip: "9,333 B",
    ceiling: 9479,
  },
  presetPresence: {
    bytes: 8705,
    gzip: "8,705 B",
    ceiling: 8842,
  },
  presetEveryday: {
    bytes: 9874,
    gzip: "9,874 B",
    ceiling: 10010,
  },
  jsonSchemaPlugin: {
    bytes: 22145,
    gzip: "22,145 B",
    ceiling: 22280,
  },
  jsonSchemaFullFeature: {
    bytes: 24643,
    gzip: "24,643 B",
    ceiling: 24767,
  },
  fullFeature: {
    bytes: 27326,
    gzip: "27,326 B",
    ceiling: 27433,
  },
  legacyCoreGzip: 17423,
} as const;
