// GENERATED by scripts/generate-size-data.mjs — do not edit.
// Source of truth: config/size-budget.json, which scripts/measure-bundle-size.ts
// re-measures against on every build.

export const bundleSize = {
  coreOnly: {
    bytes: 8698,
    gzip: "8,698 B",
    ceiling: 8769,
  },
  onePlugin: {
    bytes: 8836,
    gzip: "8,836 B",
    ceiling: 8918,
  },
  threePlugin: {
    bytes: 9162,
    gzip: "9,162 B",
    ceiling: 9241,
  },
  sixPlugin: {
    bytes: 9574,
    gzip: "9,574 B",
    ceiling: 9672,
  },
  presetPresence: {
    bytes: 8946,
    gzip: "8,946 B",
    ceiling: 9039,
  },
  presetEveryday: {
    bytes: 10131,
    gzip: "10,131 B",
    ceiling: 10212,
  },
  jsonSchemaPlugin: {
    bytes: 23193,
    gzip: "23,193 B",
    ceiling: 23328,
  },
  jsonSchemaFullFeature: {
    bytes: 25642,
    gzip: "25,642 B",
    ceiling: 25766,
  },
  fullFeature: {
    bytes: 28397,
    gzip: "28,397 B",
    ceiling: 28504,
  },
  legacyCoreGzip: 17423,
} as const;
