// GENERATED by scripts/generate-competitor-data.mjs — do not edit.
// Source of truth: config/competitor-baseline.json, written by
// bench/competitors/report-competitors.ts.

export const competitorBenchmark = {
  machine: {
    "cpuModel": "AMD Ryzen 7 5825U with Radeon Graphics",
    "logicalCores": 16,
    "platform": "win32",
    "arch": "x64",
    "nodeVersion": "v23.11.0",
    "totalMemoryGb": 15.3
  },
  libraries: [{"name":"zod","version":"4.0.14"},{"name":"valibot","version":"1.4.2"},{"name":"ajv","version":"8.20.0"},{"name":"yup","version":"1.7.1"}],
  rows: [
    {
      "shape": "singleField",
      "competitor": "zod",
      "version": "4.0.14",
      "luq": "1,807,175",
      "other": "96,959",
      "ratio": "19",
      "luqIsFaster": true,
      "comparedValues": 8,
      "disagreedValues": 0
    },
    {
      "shape": "singleField",
      "competitor": "valibot",
      "version": "1.4.2",
      "luq": "1,767,843",
      "other": "3,798,196",
      "ratio": "0.46",
      "luqIsFaster": false,
      "comparedValues": 8,
      "disagreedValues": 0
    },
    {
      "shape": "singleField",
      "competitor": "ajv",
      "version": "8.20.0",
      "luq": "1,798,110",
      "other": "24,071,744",
      "ratio": "0.07",
      "luqIsFaster": false,
      "comparedValues": 8,
      "disagreedValues": 0
    },
    {
      "shape": "singleField",
      "competitor": "yup",
      "version": "1.7.1",
      "luq": "1,856,989",
      "other": "37,308",
      "ratio": "50",
      "luqIsFaster": true,
      "comparedValues": 8,
      "disagreedValues": 0
    },
    {
      "shape": "multiField",
      "competitor": "zod",
      "version": "4.0.14",
      "luq": "828,141",
      "other": "77,105",
      "ratio": "11",
      "luqIsFaster": true,
      "comparedValues": 8,
      "disagreedValues": 0
    },
    {
      "shape": "multiField",
      "competitor": "valibot",
      "version": "1.4.2",
      "luq": "899,684",
      "other": "1,718,265",
      "ratio": "0.52",
      "luqIsFaster": false,
      "comparedValues": 8,
      "disagreedValues": 0
    },
    {
      "shape": "multiField",
      "competitor": "ajv",
      "version": "8.20.0",
      "luq": "866,105",
      "other": "9,286,181",
      "ratio": "0.09",
      "luqIsFaster": false,
      "comparedValues": 8,
      "disagreedValues": 0
    },
    {
      "shape": "multiField",
      "competitor": "yup",
      "version": "1.7.1",
      "luq": "881,736",
      "other": "34,622",
      "ratio": "25",
      "luqIsFaster": true,
      "comparedValues": 7,
      "disagreedValues": 1
    },
    {
      "shape": "nested",
      "competitor": "zod",
      "version": "4.0.14",
      "luq": "545,541",
      "other": "73,823",
      "ratio": "7.57",
      "luqIsFaster": true,
      "comparedValues": 8,
      "disagreedValues": 0
    },
    {
      "shape": "nested",
      "competitor": "valibot",
      "version": "1.4.2",
      "luq": "643,387",
      "other": "1,123,708",
      "ratio": "0.57",
      "luqIsFaster": false,
      "comparedValues": 8,
      "disagreedValues": 0
    },
    {
      "shape": "nested",
      "competitor": "ajv",
      "version": "8.20.0",
      "luq": "636,753",
      "other": "10,433,036",
      "ratio": "0.06",
      "luqIsFaster": false,
      "comparedValues": 8,
      "disagreedValues": 0
    },
    {
      "shape": "nested",
      "competitor": "yup",
      "version": "1.7.1",
      "luq": "621,621",
      "other": "21,503",
      "ratio": "29",
      "luqIsFaster": true,
      "comparedValues": 8,
      "disagreedValues": 0
    },
    {
      "shape": "array",
      "competitor": "zod",
      "version": "4.0.14",
      "luq": "29,422",
      "other": "33,877",
      "ratio": "0.89",
      "luqIsFaster": false,
      "comparedValues": 8,
      "disagreedValues": 0
    },
    {
      "shape": "array",
      "competitor": "valibot",
      "version": "1.4.2",
      "luq": "30,511",
      "other": "54,035",
      "ratio": "0.57",
      "luqIsFaster": false,
      "comparedValues": 8,
      "disagreedValues": 0
    },
    {
      "shape": "array",
      "competitor": "ajv",
      "version": "8.20.0",
      "luq": "29,961",
      "other": "457,892",
      "ratio": "0.07",
      "luqIsFaster": false,
      "comparedValues": 8,
      "disagreedValues": 0
    },
    {
      "shape": "array",
      "competitor": "yup",
      "version": "1.7.1",
      "luq": "29,723",
      "other": "1,457",
      "ratio": "20",
      "luqIsFaster": true,
      "comparedValues": 8,
      "disagreedValues": 0
    }
  ],
  disagreements: [
    {
      "shape": "multiField",
      "competitor": "yup",
      "luqSaid": false,
      "value": "{\"name\":\"Alexandra\",\"email\":\".alexandra@example.com\",\"age\":34}"
    }
  ],
  luqWins: 7,
  total: 16,
} as const;
