// GENERATED by scripts/generate-competitor-data.mjs — do not edit.
// Source of truth: config/competitor-baseline.json, written by
// bench/competitors/report-competitors.ts.

export const competitorBenchmark = {
  libraries: [{"name":"zod","version":"4.0.14"},{"name":"valibot","version":"1.4.2"},{"name":"ajv","version":"8.20.0"},{"name":"yup","version":"1.7.1"}],
  rows: [
    {
      "shape": "singleField",
      "competitor": "zod",
      "version": "4.0.14",
      "luq": "1,739,626",
      "other": "86,244",
      "ratio": "19",
      "luqIsFaster": true,
      "comparedValues": 8,
      "disagreedValues": 0
    },
    {
      "shape": "singleField",
      "competitor": "valibot",
      "version": "1.4.2",
      "luq": "1,965,425",
      "other": "2,868,045",
      "ratio": "0.69",
      "luqIsFaster": false,
      "comparedValues": 8,
      "disagreedValues": 0
    },
    {
      "shape": "singleField",
      "competitor": "ajv",
      "version": "8.20.0",
      "luq": "1,917,658",
      "other": "19,280,651",
      "ratio": "0.10",
      "luqIsFaster": false,
      "comparedValues": 8,
      "disagreedValues": 0
    },
    {
      "shape": "singleField",
      "competitor": "yup",
      "version": "1.7.1",
      "luq": "1,874,528",
      "other": "69,003",
      "ratio": "27",
      "luqIsFaster": true,
      "comparedValues": 8,
      "disagreedValues": 0
    },
    {
      "shape": "multiField",
      "competitor": "zod",
      "version": "4.0.14",
      "luq": "846,727",
      "other": "75,171",
      "ratio": "11",
      "luqIsFaster": true,
      "comparedValues": 8,
      "disagreedValues": 0
    },
    {
      "shape": "multiField",
      "competitor": "valibot",
      "version": "1.4.2",
      "luq": "968,123",
      "other": "1,256,948",
      "ratio": "0.77",
      "luqIsFaster": false,
      "comparedValues": 8,
      "disagreedValues": 0
    },
    {
      "shape": "multiField",
      "competitor": "ajv",
      "version": "8.20.0",
      "luq": "959,329",
      "other": "7,718,556",
      "ratio": "0.13",
      "luqIsFaster": false,
      "comparedValues": 8,
      "disagreedValues": 0
    },
    {
      "shape": "multiField",
      "competitor": "yup",
      "version": "1.7.1",
      "luq": "984,634",
      "other": "64,103",
      "ratio": "15",
      "luqIsFaster": true,
      "comparedValues": 7,
      "disagreedValues": 1
    },
    {
      "shape": "nested",
      "competitor": "zod",
      "version": "4.0.14",
      "luq": "708,607",
      "other": "73,101",
      "ratio": "9.83",
      "luqIsFaster": true,
      "comparedValues": 8,
      "disagreedValues": 0
    },
    {
      "shape": "nested",
      "competitor": "valibot",
      "version": "1.4.2",
      "luq": "767,359",
      "other": "874,639",
      "ratio": "0.88",
      "luqIsFaster": false,
      "comparedValues": 8,
      "disagreedValues": 0
    },
    {
      "shape": "nested",
      "competitor": "ajv",
      "version": "8.20.0",
      "luq": "788,317",
      "other": "7,474,877",
      "ratio": "0.11",
      "luqIsFaster": false,
      "comparedValues": 8,
      "disagreedValues": 0
    },
    {
      "shape": "nested",
      "competitor": "yup",
      "version": "1.7.1",
      "luq": "739,007",
      "other": "42,471",
      "ratio": "17",
      "luqIsFaster": true,
      "comparedValues": 8,
      "disagreedValues": 0
    },
    {
      "shape": "array",
      "competitor": "zod",
      "version": "4.0.14",
      "luq": "8,828",
      "other": "21,789",
      "ratio": "0.40",
      "luqIsFaster": false,
      "comparedValues": 8,
      "disagreedValues": 0
    },
    {
      "shape": "array",
      "competitor": "valibot",
      "version": "1.4.2",
      "luq": "9,039",
      "other": "39,554",
      "ratio": "0.23",
      "luqIsFaster": false,
      "comparedValues": 8,
      "disagreedValues": 0
    },
    {
      "shape": "array",
      "competitor": "ajv",
      "version": "8.20.0",
      "luq": "8,896",
      "other": "375,644",
      "ratio": "0.02",
      "luqIsFaster": false,
      "comparedValues": 8,
      "disagreedValues": 0
    },
    {
      "shape": "array",
      "competitor": "yup",
      "version": "1.7.1",
      "luq": "9,032",
      "other": "2,826",
      "ratio": "3.20",
      "luqIsFaster": true,
      "comparedValues": 8,
      "disagreedValues": 0
    }
  ],
  disagreements: [
    {
      "shape": "multiField",
      "competitor": "yup",
      "luqSaid": false,
      "value": "{\"name\":\"Alexandra\",\"email\":\".alexandra@example.com\",\"age\":34}"
    }
  ],
  luqWins: 7,
  total: 16,
} as const;
