// GENERATED by scripts/generate-conformance-data.mjs — do not edit.
// Source of truth: config/json-schema-suite.json, which
// test/integration/json-schema-suite.test.ts asserts in both directions.

export const conformance = {
  passingCases: 855,
  caseCount: 929,
  failingCases: 74,
  skippedCases: 74,
  percent: "92.03",
  fraction: "855 / 929",
  headline: "855 / 929 = 92.03%",
  suiteCommit: "f6fd52a0a95472e079cbfc6ef7f089702b80e045",
  suiteDigest: "sha256:323c37914b8c8a41176ccd343cfc110659039c740d380d50ca71f96a5b4860aa",
  fileCount: 37,
  groupCount: 258,
  validCases: 551,
  invalidCases: 378,
  passingValidCases: 523,
  passingInvalidCases: 332,
  validPercent: "94.92",
  invalidPercent: "87.83",
  trivialPercent: "59.31",
} as const;
