// GENERATED by scripts/generate-package-data.mjs — do not edit.
// Source of truth: the repository's package.json, which is what npm publishes.

export const packageInfo = {
  name: "@maroonedog/luq",
  version: "2.1.0",
  tag: "v2.1.0",
  install: "npm install @maroonedog/luq",
} as const;
