// GENERATED FILE - do not edit by hand.
// Generated by scripts/catalog/build-plugin-catalog.ts out of the plugin directory structure.

import type { PluginNotImported } from "./plugin-not-imported.types";

/**
 * Which plugin offers which chain method, on which slot.
 *
 * This exists so that calling a method whose plugin was never imported is a
 * NAMED compile error instead of `Property 'min' does not exist on type
 * 'FieldChain<...>'`. That message states a fact and leaves the reader to
 * work out whether they mistyped, picked a method for the wrong type, or
 * simply forgot the import — three different fixes.
 *
 * Literal strings only. Nothing here imports a plugin, so the chain layer
 * gains no dependency on the plugin layer; what it gains is the plugin
 * layer's NAMES, which is what an error message has to say out loud.
 */
export interface SlotCatalog {
  readonly any: {
    readonly custom: PluginNotImported<
      "custom",
      "customPlugin",
      "@maroonedog/luq/plugins/custom"
    >;
    readonly jsonSchema: PluginNotImported<
      "jsonSchema",
      "jsonSchemaPlugin",
      "@maroonedog/luq/plugins/jsonSchema"
    >;
    readonly jsonSchemaFullFeature: PluginNotImported<
      "jsonSchemaFullFeature",
      "jsonSchemaFullFeaturePlugin",
      "@maroonedog/luq/plugins/jsonSchemaFullFeature"
    >;
    readonly literal: PluginNotImported<
      "literal",
      "literalPlugin",
      "@maroonedog/luq/plugins/literal"
    >;
    readonly nullable: PluginNotImported<
      "nullable",
      "nullablePlugin",
      "@maroonedog/luq/plugins/nullable"
    >;
    readonly optional: PluginNotImported<
      "optional",
      "optionalPlugin",
      "@maroonedog/luq/plugins/optional"
    >;
    readonly optionalIf: PluginNotImported<
      "optionalIf",
      "optionalIfPlugin",
      "@maroonedog/luq/plugins/optionalIf"
    >;
    readonly orFail: PluginNotImported<
      "orFail",
      "orFailPlugin",
      "@maroonedog/luq/plugins/orFail"
    >;
    readonly required: PluginNotImported<
      "required",
      "requiredPlugin",
      "@maroonedog/luq/plugins/required"
    >;
    readonly requiredIf: PluginNotImported<
      "requiredIf",
      "requiredIfPlugin",
      "@maroonedog/luq/plugins/requiredIf"
    >;
    readonly skip: PluginNotImported<
      "skip",
      "skipPlugin",
      "@maroonedog/luq/plugins/skip"
    >;
    readonly validateIf: PluginNotImported<
      "validateIf",
      "validateIfPlugin",
      "@maroonedog/luq/plugins/validateIf"
    >;
  };
  readonly array: {
    readonly compareField: PluginNotImported<
      "compareField",
      "compareFieldPlugin",
      "@maroonedog/luq/plugins/compareField"
    >;
    readonly conditionalSchema: PluginNotImported<
      "conditionalSchema",
      "conditionalSchemaPlugin",
      "@maroonedog/luq/plugins/conditionalSchema"
    >;
    readonly contains: PluginNotImported<
      "contains",
      "arrayContainsPlugin",
      "@maroonedog/luq/plugins/arrayContains"
    >;
    readonly custom: PluginNotImported<
      "custom",
      "customPlugin",
      "@maroonedog/luq/plugins/custom"
    >;
    readonly each: PluginNotImported<
      "each",
      "arrayEachPlugin",
      "@maroonedog/luq/plugins/arrayEach"
    >;
    readonly fromContext: PluginNotImported<
      "fromContext",
      "fromContextPlugin",
      "@maroonedog/luq/plugins/fromContext"
    >;
    readonly includes: PluginNotImported<
      "includes",
      "arrayIncludesPlugin",
      "@maroonedog/luq/plugins/arrayIncludes"
    >;
    readonly jsonSchema: PluginNotImported<
      "jsonSchema",
      "jsonSchemaPlugin",
      "@maroonedog/luq/plugins/jsonSchema"
    >;
    readonly jsonSchemaFullFeature: PluginNotImported<
      "jsonSchemaFullFeature",
      "jsonSchemaFullFeaturePlugin",
      "@maroonedog/luq/plugins/jsonSchemaFullFeature"
    >;
    readonly literal: PluginNotImported<
      "literal",
      "literalPlugin",
      "@maroonedog/luq/plugins/literal"
    >;
    readonly maxLength: PluginNotImported<
      "maxLength",
      "arrayMaxLengthPlugin",
      "@maroonedog/luq/plugins/arrayMaxLength"
    >;
    readonly minLength: PluginNotImported<
      "minLength",
      "arrayMinLengthPlugin",
      "@maroonedog/luq/plugins/arrayMinLength"
    >;
    readonly nullable: PluginNotImported<
      "nullable",
      "nullablePlugin",
      "@maroonedog/luq/plugins/nullable"
    >;
    readonly optional: PluginNotImported<
      "optional",
      "optionalPlugin",
      "@maroonedog/luq/plugins/optional"
    >;
    readonly optionalIf: PluginNotImported<
      "optionalIf",
      "optionalIfPlugin",
      "@maroonedog/luq/plugins/optionalIf"
    >;
    readonly orFail: PluginNotImported<
      "orFail",
      "orFailPlugin",
      "@maroonedog/luq/plugins/orFail"
    >;
    readonly readOnly: PluginNotImported<
      "readOnly",
      "readOnlyPlugin",
      "@maroonedog/luq/plugins/readOnly"
    >;
    readonly recursively: PluginNotImported<
      "recursively",
      "objectRecursivelyPlugin",
      "@maroonedog/luq/plugins/objectRecursively"
    >;
    readonly required: PluginNotImported<
      "required",
      "requiredPlugin",
      "@maroonedog/luq/plugins/required"
    >;
    readonly requiredIf: PluginNotImported<
      "requiredIf",
      "requiredIfPlugin",
      "@maroonedog/luq/plugins/requiredIf"
    >;
    readonly skip: PluginNotImported<
      "skip",
      "skipPlugin",
      "@maroonedog/luq/plugins/skip"
    >;
    readonly stitch: PluginNotImported<
      "stitch",
      "stitchPlugin",
      "@maroonedog/luq/plugins/stitch"
    >;
    readonly stitchWith: PluginNotImported<
      "stitchWith",
      "stitchWithPlugin",
      "@maroonedog/luq/plugins/stitchWith"
    >;
    readonly transform: PluginNotImported<
      "transform",
      "transformPlugin",
      "@maroonedog/luq/plugins/transform"
    >;
    readonly unique: PluginNotImported<
      "unique",
      "arrayUniquePlugin",
      "@maroonedog/luq/plugins/arrayUnique"
    >;
    readonly validateIf: PluginNotImported<
      "validateIf",
      "validateIfPlugin",
      "@maroonedog/luq/plugins/validateIf"
    >;
    readonly writeOnly: PluginNotImported<
      "writeOnly",
      "writeOnlyPlugin",
      "@maroonedog/luq/plugins/writeOnly"
    >;
  };
  readonly boolean: {
    readonly compareField: PluginNotImported<
      "compareField",
      "compareFieldPlugin",
      "@maroonedog/luq/plugins/compareField"
    >;
    readonly conditionalSchema: PluginNotImported<
      "conditionalSchema",
      "conditionalSchemaPlugin",
      "@maroonedog/luq/plugins/conditionalSchema"
    >;
    readonly custom: PluginNotImported<
      "custom",
      "customPlugin",
      "@maroonedog/luq/plugins/custom"
    >;
    readonly falsy: PluginNotImported<
      "falsy",
      "booleanFalsyPlugin",
      "@maroonedog/luq/plugins/booleanFalsy"
    >;
    readonly fromContext: PluginNotImported<
      "fromContext",
      "fromContextPlugin",
      "@maroonedog/luq/plugins/fromContext"
    >;
    readonly jsonSchema: PluginNotImported<
      "jsonSchema",
      "jsonSchemaPlugin",
      "@maroonedog/luq/plugins/jsonSchema"
    >;
    readonly jsonSchemaFullFeature: PluginNotImported<
      "jsonSchemaFullFeature",
      "jsonSchemaFullFeaturePlugin",
      "@maroonedog/luq/plugins/jsonSchemaFullFeature"
    >;
    readonly literal: PluginNotImported<
      "literal",
      "literalPlugin",
      "@maroonedog/luq/plugins/literal"
    >;
    readonly nullable: PluginNotImported<
      "nullable",
      "nullablePlugin",
      "@maroonedog/luq/plugins/nullable"
    >;
    readonly oneOf: PluginNotImported<
      "oneOf",
      "oneOfPlugin",
      "@maroonedog/luq/plugins/oneOf"
    >;
    readonly optional: PluginNotImported<
      "optional",
      "optionalPlugin",
      "@maroonedog/luq/plugins/optional"
    >;
    readonly optionalIf: PluginNotImported<
      "optionalIf",
      "optionalIfPlugin",
      "@maroonedog/luq/plugins/optionalIf"
    >;
    readonly orFail: PluginNotImported<
      "orFail",
      "orFailPlugin",
      "@maroonedog/luq/plugins/orFail"
    >;
    readonly readOnly: PluginNotImported<
      "readOnly",
      "readOnlyPlugin",
      "@maroonedog/luq/plugins/readOnly"
    >;
    readonly required: PluginNotImported<
      "required",
      "requiredPlugin",
      "@maroonedog/luq/plugins/required"
    >;
    readonly requiredIf: PluginNotImported<
      "requiredIf",
      "requiredIfPlugin",
      "@maroonedog/luq/plugins/requiredIf"
    >;
    readonly skip: PluginNotImported<
      "skip",
      "skipPlugin",
      "@maroonedog/luq/plugins/skip"
    >;
    readonly stitch: PluginNotImported<
      "stitch",
      "stitchPlugin",
      "@maroonedog/luq/plugins/stitch"
    >;
    readonly stitchWith: PluginNotImported<
      "stitchWith",
      "stitchWithPlugin",
      "@maroonedog/luq/plugins/stitchWith"
    >;
    readonly transform: PluginNotImported<
      "transform",
      "transformPlugin",
      "@maroonedog/luq/plugins/transform"
    >;
    readonly truthy: PluginNotImported<
      "truthy",
      "booleanTruthyPlugin",
      "@maroonedog/luq/plugins/booleanTruthy"
    >;
    readonly validateIf: PluginNotImported<
      "validateIf",
      "validateIfPlugin",
      "@maroonedog/luq/plugins/validateIf"
    >;
    readonly writeOnly: PluginNotImported<
      "writeOnly",
      "writeOnlyPlugin",
      "@maroonedog/luq/plugins/writeOnly"
    >;
  };
  readonly date: {
    readonly compareField: PluginNotImported<
      "compareField",
      "compareFieldPlugin",
      "@maroonedog/luq/plugins/compareField"
    >;
    readonly custom: PluginNotImported<
      "custom",
      "customPlugin",
      "@maroonedog/luq/plugins/custom"
    >;
    readonly fromContext: PluginNotImported<
      "fromContext",
      "fromContextPlugin",
      "@maroonedog/luq/plugins/fromContext"
    >;
    readonly jsonSchema: PluginNotImported<
      "jsonSchema",
      "jsonSchemaPlugin",
      "@maroonedog/luq/plugins/jsonSchema"
    >;
    readonly jsonSchemaFullFeature: PluginNotImported<
      "jsonSchemaFullFeature",
      "jsonSchemaFullFeaturePlugin",
      "@maroonedog/luq/plugins/jsonSchemaFullFeature"
    >;
    readonly literal: PluginNotImported<
      "literal",
      "literalPlugin",
      "@maroonedog/luq/plugins/literal"
    >;
    readonly nullable: PluginNotImported<
      "nullable",
      "nullablePlugin",
      "@maroonedog/luq/plugins/nullable"
    >;
    readonly optional: PluginNotImported<
      "optional",
      "optionalPlugin",
      "@maroonedog/luq/plugins/optional"
    >;
    readonly optionalIf: PluginNotImported<
      "optionalIf",
      "optionalIfPlugin",
      "@maroonedog/luq/plugins/optionalIf"
    >;
    readonly orFail: PluginNotImported<
      "orFail",
      "orFailPlugin",
      "@maroonedog/luq/plugins/orFail"
    >;
    readonly readOnly: PluginNotImported<
      "readOnly",
      "readOnlyPlugin",
      "@maroonedog/luq/plugins/readOnly"
    >;
    readonly required: PluginNotImported<
      "required",
      "requiredPlugin",
      "@maroonedog/luq/plugins/required"
    >;
    readonly requiredIf: PluginNotImported<
      "requiredIf",
      "requiredIfPlugin",
      "@maroonedog/luq/plugins/requiredIf"
    >;
    readonly skip: PluginNotImported<
      "skip",
      "skipPlugin",
      "@maroonedog/luq/plugins/skip"
    >;
    readonly stitch: PluginNotImported<
      "stitch",
      "stitchPlugin",
      "@maroonedog/luq/plugins/stitch"
    >;
    readonly stitchWith: PluginNotImported<
      "stitchWith",
      "stitchWithPlugin",
      "@maroonedog/luq/plugins/stitchWith"
    >;
    readonly transform: PluginNotImported<
      "transform",
      "transformPlugin",
      "@maroonedog/luq/plugins/transform"
    >;
    readonly validateIf: PluginNotImported<
      "validateIf",
      "validateIfPlugin",
      "@maroonedog/luq/plugins/validateIf"
    >;
    readonly writeOnly: PluginNotImported<
      "writeOnly",
      "writeOnlyPlugin",
      "@maroonedog/luq/plugins/writeOnly"
    >;
  };
  readonly number: {
    readonly compareField: PluginNotImported<
      "compareField",
      "compareFieldPlugin",
      "@maroonedog/luq/plugins/compareField"
    >;
    readonly conditionalSchema: PluginNotImported<
      "conditionalSchema",
      "conditionalSchemaPlugin",
      "@maroonedog/luq/plugins/conditionalSchema"
    >;
    readonly custom: PluginNotImported<
      "custom",
      "customPlugin",
      "@maroonedog/luq/plugins/custom"
    >;
    readonly finite: PluginNotImported<
      "finite",
      "numberFinitePlugin",
      "@maroonedog/luq/plugins/numberFinite"
    >;
    readonly fromContext: PluginNotImported<
      "fromContext",
      "fromContextPlugin",
      "@maroonedog/luq/plugins/fromContext"
    >;
    readonly integer: PluginNotImported<
      "integer",
      "numberIntegerPlugin",
      "@maroonedog/luq/plugins/numberInteger"
    >;
    readonly jsonSchema: PluginNotImported<
      "jsonSchema",
      "jsonSchemaPlugin",
      "@maroonedog/luq/plugins/jsonSchema"
    >;
    readonly jsonSchemaFullFeature: PluginNotImported<
      "jsonSchemaFullFeature",
      "jsonSchemaFullFeaturePlugin",
      "@maroonedog/luq/plugins/jsonSchemaFullFeature"
    >;
    readonly literal: PluginNotImported<
      "literal",
      "literalPlugin",
      "@maroonedog/luq/plugins/literal"
    >;
    readonly max: PluginNotImported<
      "max",
      "numberMaxPlugin",
      "@maroonedog/luq/plugins/numberMax"
    >;
    readonly min: PluginNotImported<
      "min",
      "numberMinPlugin",
      "@maroonedog/luq/plugins/numberMin"
    >;
    readonly multipleOf: PluginNotImported<
      "multipleOf",
      "numberMultipleOfPlugin",
      "@maroonedog/luq/plugins/numberMultipleOf"
    >;
    readonly negative: PluginNotImported<
      "negative",
      "numberNegativePlugin",
      "@maroonedog/luq/plugins/numberNegative"
    >;
    readonly nullable: PluginNotImported<
      "nullable",
      "nullablePlugin",
      "@maroonedog/luq/plugins/nullable"
    >;
    readonly oneOf: PluginNotImported<
      "oneOf",
      "oneOfPlugin",
      "@maroonedog/luq/plugins/oneOf"
    >;
    readonly optional: PluginNotImported<
      "optional",
      "optionalPlugin",
      "@maroonedog/luq/plugins/optional"
    >;
    readonly optionalIf: PluginNotImported<
      "optionalIf",
      "optionalIfPlugin",
      "@maroonedog/luq/plugins/optionalIf"
    >;
    readonly orFail: PluginNotImported<
      "orFail",
      "orFailPlugin",
      "@maroonedog/luq/plugins/orFail"
    >;
    readonly positive: PluginNotImported<
      "positive",
      "numberPositivePlugin",
      "@maroonedog/luq/plugins/numberPositive"
    >;
    readonly range: PluginNotImported<
      "range",
      "numberRangePlugin",
      "@maroonedog/luq/plugins/numberRange"
    >;
    readonly readOnly: PluginNotImported<
      "readOnly",
      "readOnlyPlugin",
      "@maroonedog/luq/plugins/readOnly"
    >;
    readonly required: PluginNotImported<
      "required",
      "requiredPlugin",
      "@maroonedog/luq/plugins/required"
    >;
    readonly requiredIf: PluginNotImported<
      "requiredIf",
      "requiredIfPlugin",
      "@maroonedog/luq/plugins/requiredIf"
    >;
    readonly skip: PluginNotImported<
      "skip",
      "skipPlugin",
      "@maroonedog/luq/plugins/skip"
    >;
    readonly stitch: PluginNotImported<
      "stitch",
      "stitchPlugin",
      "@maroonedog/luq/plugins/stitch"
    >;
    readonly stitchWith: PluginNotImported<
      "stitchWith",
      "stitchWithPlugin",
      "@maroonedog/luq/plugins/stitchWith"
    >;
    readonly transform: PluginNotImported<
      "transform",
      "transformPlugin",
      "@maroonedog/luq/plugins/transform"
    >;
    readonly validateIf: PluginNotImported<
      "validateIf",
      "validateIfPlugin",
      "@maroonedog/luq/plugins/validateIf"
    >;
    readonly writeOnly: PluginNotImported<
      "writeOnly",
      "writeOnlyPlugin",
      "@maroonedog/luq/plugins/writeOnly"
    >;
  };
  readonly object: {
    readonly additionalProperties: PluginNotImported<
      "additionalProperties",
      "objectAdditionalPropertiesPlugin",
      "@maroonedog/luq/plugins/objectAdditionalProperties"
    >;
    readonly additionalPropertiesSchema: PluginNotImported<
      "additionalPropertiesSchema",
      "objectAdditionalPropertiesSchemaPlugin",
      "@maroonedog/luq/plugins/objectAdditionalProperties"
    >;
    readonly compareField: PluginNotImported<
      "compareField",
      "compareFieldPlugin",
      "@maroonedog/luq/plugins/compareField"
    >;
    readonly conditionalSchema: PluginNotImported<
      "conditionalSchema",
      "conditionalSchemaPlugin",
      "@maroonedog/luq/plugins/conditionalSchema"
    >;
    readonly custom: PluginNotImported<
      "custom",
      "customPlugin",
      "@maroonedog/luq/plugins/custom"
    >;
    readonly dependentRequired: PluginNotImported<
      "dependentRequired",
      "objectDependentRequiredPlugin",
      "@maroonedog/luq/plugins/objectDependentRequired"
    >;
    readonly dependentSchemas: PluginNotImported<
      "dependentSchemas",
      "objectDependentSchemasPlugin",
      "@maroonedog/luq/plugins/objectDependentSchemas"
    >;
    readonly fromContext: PluginNotImported<
      "fromContext",
      "fromContextPlugin",
      "@maroonedog/luq/plugins/fromContext"
    >;
    readonly jsonSchema: PluginNotImported<
      "jsonSchema",
      "jsonSchemaPlugin",
      "@maroonedog/luq/plugins/jsonSchema"
    >;
    readonly jsonSchemaFullFeature: PluginNotImported<
      "jsonSchemaFullFeature",
      "jsonSchemaFullFeaturePlugin",
      "@maroonedog/luq/plugins/jsonSchemaFullFeature"
    >;
    readonly literal: PluginNotImported<
      "literal",
      "literalPlugin",
      "@maroonedog/luq/plugins/literal"
    >;
    readonly maxProperties: PluginNotImported<
      "maxProperties",
      "objectMaxPropertiesPlugin",
      "@maroonedog/luq/plugins/objectMaxProperties"
    >;
    readonly minProperties: PluginNotImported<
      "minProperties",
      "objectMinPropertiesPlugin",
      "@maroonedog/luq/plugins/objectMinProperties"
    >;
    readonly nullable: PluginNotImported<
      "nullable",
      "nullablePlugin",
      "@maroonedog/luq/plugins/nullable"
    >;
    readonly object: PluginNotImported<
      "object",
      "objectPlugin",
      "@maroonedog/luq/plugins/object"
    >;
    readonly optional: PluginNotImported<
      "optional",
      "optionalPlugin",
      "@maroonedog/luq/plugins/optional"
    >;
    readonly optionalIf: PluginNotImported<
      "optionalIf",
      "optionalIfPlugin",
      "@maroonedog/luq/plugins/optionalIf"
    >;
    readonly orFail: PluginNotImported<
      "orFail",
      "orFailPlugin",
      "@maroonedog/luq/plugins/orFail"
    >;
    readonly patternProperties: PluginNotImported<
      "patternProperties",
      "objectPatternPropertiesPlugin",
      "@maroonedog/luq/plugins/objectPatternProperties"
    >;
    readonly propertyNames: PluginNotImported<
      "propertyNames",
      "objectPropertyNamesPlugin",
      "@maroonedog/luq/plugins/objectPropertyNames"
    >;
    readonly readOnly: PluginNotImported<
      "readOnly",
      "readOnlyPlugin",
      "@maroonedog/luq/plugins/readOnly"
    >;
    readonly recursively: PluginNotImported<
      "recursively",
      "objectRecursivelyPlugin",
      "@maroonedog/luq/plugins/objectRecursively"
    >;
    readonly required: PluginNotImported<
      "required",
      "requiredPlugin",
      "@maroonedog/luq/plugins/required"
    >;
    readonly requiredIf: PluginNotImported<
      "requiredIf",
      "requiredIfPlugin",
      "@maroonedog/luq/plugins/requiredIf"
    >;
    readonly skip: PluginNotImported<
      "skip",
      "skipPlugin",
      "@maroonedog/luq/plugins/skip"
    >;
    readonly stitch: PluginNotImported<
      "stitch",
      "stitchPlugin",
      "@maroonedog/luq/plugins/stitch"
    >;
    readonly stitchWith: PluginNotImported<
      "stitchWith",
      "stitchWithPlugin",
      "@maroonedog/luq/plugins/stitchWith"
    >;
    readonly transform: PluginNotImported<
      "transform",
      "transformPlugin",
      "@maroonedog/luq/plugins/transform"
    >;
    readonly validateIf: PluginNotImported<
      "validateIf",
      "validateIfPlugin",
      "@maroonedog/luq/plugins/validateIf"
    >;
    readonly writeOnly: PluginNotImported<
      "writeOnly",
      "writeOnlyPlugin",
      "@maroonedog/luq/plugins/writeOnly"
    >;
  };
  readonly string: {
    readonly alphanumeric: PluginNotImported<
      "alphanumeric",
      "stringAlphanumericPlugin",
      "@maroonedog/luq/plugins/stringAlphanumeric"
    >;
    readonly base64: PluginNotImported<
      "base64",
      "stringBase64Plugin",
      "@maroonedog/luq/plugins/stringBase64"
    >;
    readonly compareField: PluginNotImported<
      "compareField",
      "compareFieldPlugin",
      "@maroonedog/luq/plugins/compareField"
    >;
    readonly conditionalSchema: PluginNotImported<
      "conditionalSchema",
      "conditionalSchemaPlugin",
      "@maroonedog/luq/plugins/conditionalSchema"
    >;
    readonly contentEncoding: PluginNotImported<
      "contentEncoding",
      "stringContentEncodingPlugin",
      "@maroonedog/luq/plugins/stringContentEncoding"
    >;
    readonly contentMediaType: PluginNotImported<
      "contentMediaType",
      "stringContentMediaTypePlugin",
      "@maroonedog/luq/plugins/stringContentMediaType"
    >;
    readonly custom: PluginNotImported<
      "custom",
      "customPlugin",
      "@maroonedog/luq/plugins/custom"
    >;
    readonly date: PluginNotImported<
      "date",
      "stringDatePlugin",
      "@maroonedog/luq/plugins/stringDate"
    >;
    readonly datetime: PluginNotImported<
      "datetime",
      "stringDatetimePlugin",
      "@maroonedog/luq/plugins/stringDatetime"
    >;
    readonly duration: PluginNotImported<
      "duration",
      "stringDurationPlugin",
      "@maroonedog/luq/plugins/stringDuration"
    >;
    readonly email: PluginNotImported<
      "email",
      "stringEmailPlugin",
      "@maroonedog/luq/plugins/stringEmail"
    >;
    readonly endsWith: PluginNotImported<
      "endsWith",
      "stringEndsWithPlugin",
      "@maroonedog/luq/plugins/stringEndsWith"
    >;
    readonly exactLength: PluginNotImported<
      "exactLength",
      "stringExactLengthPlugin",
      "@maroonedog/luq/plugins/stringExactLength"
    >;
    readonly fromContext: PluginNotImported<
      "fromContext",
      "fromContextPlugin",
      "@maroonedog/luq/plugins/fromContext"
    >;
    readonly hostname: PluginNotImported<
      "hostname",
      "stringHostnamePlugin",
      "@maroonedog/luq/plugins/stringHostname"
    >;
    readonly idnEmail: PluginNotImported<
      "idnEmail",
      "stringIdnEmailPlugin",
      "@maroonedog/luq/plugins/stringIdnEmail"
    >;
    readonly idnHostname: PluginNotImported<
      "idnHostname",
      "stringIdnHostnamePlugin",
      "@maroonedog/luq/plugins/stringIdnHostname"
    >;
    readonly ipv4: PluginNotImported<
      "ipv4",
      "stringIpv4Plugin",
      "@maroonedog/luq/plugins/stringIpv4"
    >;
    readonly ipv6: PluginNotImported<
      "ipv6",
      "stringIpv6Plugin",
      "@maroonedog/luq/plugins/stringIpv6"
    >;
    readonly iri: PluginNotImported<
      "iri",
      "stringIriPlugin",
      "@maroonedog/luq/plugins/stringIri"
    >;
    readonly iriReference: PluginNotImported<
      "iriReference",
      "stringIriReferencePlugin",
      "@maroonedog/luq/plugins/stringIriReference"
    >;
    readonly jsonPointer: PluginNotImported<
      "jsonPointer",
      "stringJsonPointerPlugin",
      "@maroonedog/luq/plugins/stringJsonPointer"
    >;
    readonly jsonSchema: PluginNotImported<
      "jsonSchema",
      "jsonSchemaPlugin",
      "@maroonedog/luq/plugins/jsonSchema"
    >;
    readonly jsonSchemaFullFeature: PluginNotImported<
      "jsonSchemaFullFeature",
      "jsonSchemaFullFeaturePlugin",
      "@maroonedog/luq/plugins/jsonSchemaFullFeature"
    >;
    readonly literal: PluginNotImported<
      "literal",
      "literalPlugin",
      "@maroonedog/luq/plugins/literal"
    >;
    readonly max: PluginNotImported<
      "max",
      "stringMaxPlugin",
      "@maroonedog/luq/plugins/stringMax"
    >;
    readonly min: PluginNotImported<
      "min",
      "stringMinPlugin",
      "@maroonedog/luq/plugins/stringMin"
    >;
    readonly nullable: PluginNotImported<
      "nullable",
      "nullablePlugin",
      "@maroonedog/luq/plugins/nullable"
    >;
    readonly oneOf: PluginNotImported<
      "oneOf",
      "oneOfPlugin",
      "@maroonedog/luq/plugins/oneOf"
    >;
    readonly optional: PluginNotImported<
      "optional",
      "optionalPlugin",
      "@maroonedog/luq/plugins/optional"
    >;
    readonly optionalIf: PluginNotImported<
      "optionalIf",
      "optionalIfPlugin",
      "@maroonedog/luq/plugins/optionalIf"
    >;
    readonly orFail: PluginNotImported<
      "orFail",
      "orFailPlugin",
      "@maroonedog/luq/plugins/orFail"
    >;
    readonly pattern: PluginNotImported<
      "pattern",
      "stringPatternPlugin",
      "@maroonedog/luq/plugins/stringPattern"
    >;
    readonly readOnly: PluginNotImported<
      "readOnly",
      "readOnlyPlugin",
      "@maroonedog/luq/plugins/readOnly"
    >;
    readonly regex: PluginNotImported<
      "regex",
      "stringRegexPlugin",
      "@maroonedog/luq/plugins/stringRegex"
    >;
    readonly relativeJsonPointer: PluginNotImported<
      "relativeJsonPointer",
      "stringRelativeJsonPointerPlugin",
      "@maroonedog/luq/plugins/stringRelativeJsonPointer"
    >;
    readonly required: PluginNotImported<
      "required",
      "requiredPlugin",
      "@maroonedog/luq/plugins/required"
    >;
    readonly requiredIf: PluginNotImported<
      "requiredIf",
      "requiredIfPlugin",
      "@maroonedog/luq/plugins/requiredIf"
    >;
    readonly skip: PluginNotImported<
      "skip",
      "skipPlugin",
      "@maroonedog/luq/plugins/skip"
    >;
    readonly startsWith: PluginNotImported<
      "startsWith",
      "stringStartsWithPlugin",
      "@maroonedog/luq/plugins/stringStartsWith"
    >;
    readonly stitch: PluginNotImported<
      "stitch",
      "stitchPlugin",
      "@maroonedog/luq/plugins/stitch"
    >;
    readonly stitchWith: PluginNotImported<
      "stitchWith",
      "stitchWithPlugin",
      "@maroonedog/luq/plugins/stitchWith"
    >;
    readonly time: PluginNotImported<
      "time",
      "stringTimePlugin",
      "@maroonedog/luq/plugins/stringTime"
    >;
    readonly transform: PluginNotImported<
      "transform",
      "transformPlugin",
      "@maroonedog/luq/plugins/transform"
    >;
    readonly uriReference: PluginNotImported<
      "uriReference",
      "stringUriReferencePlugin",
      "@maroonedog/luq/plugins/stringUriReference"
    >;
    readonly uriTemplate: PluginNotImported<
      "uriTemplate",
      "stringUriTemplatePlugin",
      "@maroonedog/luq/plugins/stringUriTemplate"
    >;
    readonly url: PluginNotImported<
      "url",
      "stringUrlPlugin",
      "@maroonedog/luq/plugins/stringUrl"
    >;
    readonly uuid: PluginNotImported<
      "uuid",
      "uuidPlugin",
      "@maroonedog/luq/plugins/uuid"
    >;
    readonly validateIf: PluginNotImported<
      "validateIf",
      "validateIfPlugin",
      "@maroonedog/luq/plugins/validateIf"
    >;
    readonly writeOnly: PluginNotImported<
      "writeOnly",
      "writeOnlyPlugin",
      "@maroonedog/luq/plugins/writeOnly"
    >;
  };
  readonly tuple: {
    readonly builder: PluginNotImported<
      "builder",
      "tupleBuilderPlugin",
      "@maroonedog/luq/plugins/tupleBuilder"
    >;
    readonly compareField: PluginNotImported<
      "compareField",
      "compareFieldPlugin",
      "@maroonedog/luq/plugins/compareField"
    >;
    readonly contains: PluginNotImported<
      "contains",
      "arrayContainsPlugin",
      "@maroonedog/luq/plugins/arrayContains"
    >;
    readonly custom: PluginNotImported<
      "custom",
      "customPlugin",
      "@maroonedog/luq/plugins/custom"
    >;
    readonly each: PluginNotImported<
      "each",
      "arrayEachPlugin",
      "@maroonedog/luq/plugins/arrayEach"
    >;
    readonly fromContext: PluginNotImported<
      "fromContext",
      "fromContextPlugin",
      "@maroonedog/luq/plugins/fromContext"
    >;
    readonly includes: PluginNotImported<
      "includes",
      "arrayIncludesPlugin",
      "@maroonedog/luq/plugins/arrayIncludes"
    >;
    readonly jsonSchema: PluginNotImported<
      "jsonSchema",
      "jsonSchemaPlugin",
      "@maroonedog/luq/plugins/jsonSchema"
    >;
    readonly jsonSchemaFullFeature: PluginNotImported<
      "jsonSchemaFullFeature",
      "jsonSchemaFullFeaturePlugin",
      "@maroonedog/luq/plugins/jsonSchemaFullFeature"
    >;
    readonly literal: PluginNotImported<
      "literal",
      "literalPlugin",
      "@maroonedog/luq/plugins/literal"
    >;
    readonly maxLength: PluginNotImported<
      "maxLength",
      "arrayMaxLengthPlugin",
      "@maroonedog/luq/plugins/arrayMaxLength"
    >;
    readonly minLength: PluginNotImported<
      "minLength",
      "arrayMinLengthPlugin",
      "@maroonedog/luq/plugins/arrayMinLength"
    >;
    readonly nullable: PluginNotImported<
      "nullable",
      "nullablePlugin",
      "@maroonedog/luq/plugins/nullable"
    >;
    readonly optional: PluginNotImported<
      "optional",
      "optionalPlugin",
      "@maroonedog/luq/plugins/optional"
    >;
    readonly optionalIf: PluginNotImported<
      "optionalIf",
      "optionalIfPlugin",
      "@maroonedog/luq/plugins/optionalIf"
    >;
    readonly orFail: PluginNotImported<
      "orFail",
      "orFailPlugin",
      "@maroonedog/luq/plugins/orFail"
    >;
    readonly required: PluginNotImported<
      "required",
      "requiredPlugin",
      "@maroonedog/luq/plugins/required"
    >;
    readonly requiredIf: PluginNotImported<
      "requiredIf",
      "requiredIfPlugin",
      "@maroonedog/luq/plugins/requiredIf"
    >;
    readonly skip: PluginNotImported<
      "skip",
      "skipPlugin",
      "@maroonedog/luq/plugins/skip"
    >;
    readonly stitch: PluginNotImported<
      "stitch",
      "stitchPlugin",
      "@maroonedog/luq/plugins/stitch"
    >;
    readonly stitchWith: PluginNotImported<
      "stitchWith",
      "stitchWithPlugin",
      "@maroonedog/luq/plugins/stitchWith"
    >;
    readonly unique: PluginNotImported<
      "unique",
      "arrayUniquePlugin",
      "@maroonedog/luq/plugins/arrayUnique"
    >;
    readonly validateIf: PluginNotImported<
      "validateIf",
      "validateIfPlugin",
      "@maroonedog/luq/plugins/validateIf"
    >;
  };
  readonly union: {
    readonly compareField: PluginNotImported<
      "compareField",
      "compareFieldPlugin",
      "@maroonedog/luq/plugins/compareField"
    >;
    readonly custom: PluginNotImported<
      "custom",
      "customPlugin",
      "@maroonedog/luq/plugins/custom"
    >;
    readonly fromContext: PluginNotImported<
      "fromContext",
      "fromContextPlugin",
      "@maroonedog/luq/plugins/fromContext"
    >;
    readonly guard: PluginNotImported<
      "guard",
      "unionGuardPlugin",
      "@maroonedog/luq/plugins/unionGuard"
    >;
    readonly jsonSchema: PluginNotImported<
      "jsonSchema",
      "jsonSchemaPlugin",
      "@maroonedog/luq/plugins/jsonSchema"
    >;
    readonly jsonSchemaFullFeature: PluginNotImported<
      "jsonSchemaFullFeature",
      "jsonSchemaFullFeaturePlugin",
      "@maroonedog/luq/plugins/jsonSchemaFullFeature"
    >;
    readonly literal: PluginNotImported<
      "literal",
      "literalPlugin",
      "@maroonedog/luq/plugins/literal"
    >;
    readonly nullable: PluginNotImported<
      "nullable",
      "nullablePlugin",
      "@maroonedog/luq/plugins/nullable"
    >;
    readonly optional: PluginNotImported<
      "optional",
      "optionalPlugin",
      "@maroonedog/luq/plugins/optional"
    >;
    readonly optionalIf: PluginNotImported<
      "optionalIf",
      "optionalIfPlugin",
      "@maroonedog/luq/plugins/optionalIf"
    >;
    readonly orFail: PluginNotImported<
      "orFail",
      "orFailPlugin",
      "@maroonedog/luq/plugins/orFail"
    >;
    readonly required: PluginNotImported<
      "required",
      "requiredPlugin",
      "@maroonedog/luq/plugins/required"
    >;
    readonly requiredIf: PluginNotImported<
      "requiredIf",
      "requiredIfPlugin",
      "@maroonedog/luq/plugins/requiredIf"
    >;
    readonly skip: PluginNotImported<
      "skip",
      "skipPlugin",
      "@maroonedog/luq/plugins/skip"
    >;
    readonly stitch: PluginNotImported<
      "stitch",
      "stitchPlugin",
      "@maroonedog/luq/plugins/stitch"
    >;
    readonly stitchWith: PluginNotImported<
      "stitchWith",
      "stitchWithPlugin",
      "@maroonedog/luq/plugins/stitchWith"
    >;
    readonly transform: PluginNotImported<
      "transform",
      "transformPlugin",
      "@maroonedog/luq/plugins/transform"
    >;
    readonly validateIf: PluginNotImported<
      "validateIf",
      "validateIfPlugin",
      "@maroonedog/luq/plugins/validateIf"
    >;
  };
}
